#if !canImport(ObjectiveC)
import XCTest

extension FormsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FormsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FormsTests.__allTests__FormsTests),
    ]
}
#endif
